DROP TABLE IF EXISTS finance_time_series CASCADE;
DROP TABLE IF EXISTS spending CASCADE;
DROP TABLE IF EXISTS finance_entry CASCADE;
DROP TABLE IF EXISTS bank_account CASCADE;

DROP TYPE IF EXISTS BANK_ACCOUNT_ROLE;